version: '2'
services:
  db-data:
    container_name: db-data
    image: busybox:latest
    volumes:
      - ./data/mysql/var/lib/mysql:/var/lib/mysql

  db:
    # image: mariadb:5.5.49
    build: ./app/mariadb
    # container_name: mysql
    # hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=temppassword
      - MYSQL_DATABASE=db_plaintext
      - TERM=xterm
    volumes_from:
      - db-data
    volumes:
      - ./app/mariadb/conf.d:/etc/mysql/conf.d
      - ./data/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"

  wordpress-data:
    container_name: wordpress-data
    image: busybox:latest
    volumes:
      - /var/www/html

  wordpress:
    build: ./app/wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=temppassword
      - WORDPRESS_DB_NAME=db_plaintext
      - WORDPRESS_TABLE_PREFIX=wp_
    # container_name: wordpress
    # hostname: wordpress
  #  depends_on:
  #    - letsencrypt
    depends_on:
      - db
    links:
      - db
  #  ports:
  #    - 9000:9000
    volumes_from:
      - wordpress-data
    # volumes:
      # - ./data/wordpress/wordpress/wp-content:/var/www/html/wp-content
